sudo: required
services:
- docker
language: node_js
node_js:
  - "10"
env:
- NODE_ENV=testing
before_install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.2.10.tgz
  - tar xfz mongodb-linux-x86_64-3.2.10.tgz
  - export PATH=`pwd`/mongodb-linux-x86_64-3.2.10/bin:$PATH
  - mkdir -p data/db
  - mongod --dbpath=data/db &
  - sleep 3
install:
- sudo apt update -y
- sudo apt install --only-upgrade docker-ce -y
before_script:
  - mongo test --eval 'db.createCollection("IoT");'
  - mongo test --eval 'db.createCollection("ml");'
script:
- |
  echo "Updating Docker to have docker manifest command"
  curl https://get.docker.com | sh
  echo "Enabling docker client experimental features"
  mkdir -p ~/.docker
  echo '{ "experimental": "enabled" }' > ~/.docker/config.json
  docker version
# test code
- npm i
- npm run compile
- npm run test-ci
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t haegi/silex .
# test image

# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=0.2
    docker tag haegi/silex haegi/silex:arm-$TAG
    docker push haegi/silex:arm-$TAG
    docker manifest create haegi/silex:$TAG haegi/silex:arm-$TAG
    docker manifest annotate haegi/silex:$TAG haegi/silex:arm-$TAG --os linux --arch arm --variant v6
    docker manifest push haegi/silex:$TAG
    docker manifest create haegi/silex haegi/silex:arm-$TAG
    docker manifest annotate haegi/silex haegi/silex:arm-$TAG --os linux --arch arm --variant v6
    docker manifest push haegi/silex
  fi