sudo: required
services:
- docker
language: bash
script:
- apt-cache madison docker-ce
- sudo apt-get -y install docker-ce=17.05.0~ce-0~ubuntu-trusty
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t haegi/silex .
# test image

# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    docker tag haegi/silex haegi/silex:latest
    docker push haegi/silex:latest
  fi